font:
  size: 9
  normal:
    family: "Caskaydia Cove Nerd Font"
window:
  padding:
    x: 20
    y: 10
  dimensions:
    columns: 120
    lines: 40
  opacity: 0.98

cursor:
  unfocused_hollow: false
  thickness: 0
  offset:
    x: 0
    y: 0
  blinking: always
  blinking_speed: 0.5

env:
  TERM: xterm-256color

scrolling:
  history: 2000
  auto_scroll: true



carbonfox: &carbonfox

  primary:
    background: '0x1c1c1c'
    foreground: '0xf2f4f8'
  # Normal colors
  normal:
    black:   '0x282828'
    red:     '0xee5396'
    green:   '0x25be6a'
    yellow:  '0x08bdba'
    blue:    '0x78a9ff'
    magenta: '0xbe95ff'
    cyan:    '0x33b1ff'
    white:   '0xdfdfe0'
  # Bright colors
  bright:
    black:   '0x484848'
    red:     '0xf16da6'
    green:   '0x46c880'
    yellow:  '0x2dc7c4'
    blue:    '0x8cb6ff'
    magenta: '0xc8a5ff'
    cyan:    '0x52bdff'
    white:   '0xe4e4e5'
  indexed_colors:
    - { index: 16, color: '0x3ddbd9' }
    - { index: 17, color: '0xff7eb6' }
colors: *carbonfox

