#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config border_width 0

#Touchpad setup
# xinput set-prop "GXTP7863:00 27C6:01E0 Touchpad" "libinput Natural Scrolling Enabled" 1 &
# xinput set-prop "GXTP7863:00 27C6:01E0 Touchpad" "libinput Tapping Enabled" 1 &
#
#Keyboard layout setup
# setxkbmap -layout us -variant altgr-intl -option nodeadkeys

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2' 
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Restablecer los escritorios y la ventana seleccionada al inicio
bspc wm -d 1 2 3 4 5
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config focus_follows_pointer true

# Iniciar Polybar
polybar -c ~/.config/polybar/config.ini mrrevillod&

# Iniciar el demonio de notificaciones Dunst
dunst &

# Iniciar Picom con la configuración personalizada
picom -b --config ~/.config/picom/picom.conf &

# Iniciar Nitrogen
nitrogen --restore &
