
return {}
--
-- return {
--     "folke/noice.nvim",
--     event = "VeryLazy",
--     opts = {
--         lsp = {
--             override = {
--               ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
--               ["vim.lsp.util.stylize_markdown"] = true,
--               ["cmp.entry.get_documentation"] = true,
--             },
--         },
--         routes = {{
--             filter = {
--                 event = "msg_show",
--                 kind = "",
--                 find = "written",
--                 any = {
--                     { find = "%d+L, %d+B" },
--                     { find = "; after #%d+" },
--                     { find = "; before #%d+" },
--                 },
--             },
--             opts = { skip = true }
--         }},
--         presets = {
--             bottom_search = true,
--             command_palette = true,
--             long_message_to_split = true,
--             inc_rename = true,
--         },
--         cmdline = {
--             enabled = true, -- enables the Noice cmdline UI
--             view = "cmdline_popup", -- view for rendering the cmdline. Change to `cmdline` to get a classic cmdline at the bottom
--             opts = {}, -- global options for the cmdline. See section on views
--             ---@type table<string, CmdlineFormat>
--             format = {
--               -- conceal: (default=true) This will hide the text in the cmdline that matches the pattern.
--               -- view: (default is cmdline view)
--               -- opts: any options passed to the view
--               -- icon_hl_group: optional hl_group for the icon
--               -- title: set to anything or empty string to hide
--               cmdline = { pattern = "^:", icon = "", lang = "vim" },
--               search_down = { kind = "search", pattern = "^/", icon = " ", lang = "regex" },
--               search_up = { kind = "search", pattern = "^%?", icon = " ", lang = "regex" },
--               filter = { pattern = "^:%s*!", icon = "$", lang = "bash" },
--               lua = { pattern = { "^:%s*lua%s+", "^:%s*lua%s*=%s*", "^:%s*=%s*" }, icon = "", lang = "lua" },
--               help = { pattern = "^:%s*he?l?p?%s+", icon = "" },
--               input = {}, -- Used by input()
--             },
--   },
--     },
--     dependencies = {
--         "MunifTanjim/nui.nvim",
--     },
-- }
